name: Cypress Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      # 1. API-Schlüssel für die Anwendung zur Verfügung stellen
      - name: Set up environment variables (.env)
        run: echo "NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}" > .env.local

      # 2. Next.js App bauen (npm run build)
      - name: Build Next.js App
        run: npm run build

      # 3. Cypress run mit Start des Servers
      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          # Führt "npm run start" aus (startet den Build-Output)
          start: npm run start
          # Wartet, bis der Server auf Port 3000 läuft
          wait-on: "http://localhost:3000"
          browser: chrome
